export enum UnitSizeEnum {
  COMPANY_I = 'COMPANY_I',
  BATALLION_II = 'BATALLION_II',
  KAMPGRUPPE_KG = 'KAMPGRUPPE_KG',
  REGIMENT_III = 'REGIMENT_III',
  GROUP_GRP = 'GROUP_GRP',
  BRIGADE_X = 'BRIGADE_X',
  DIVISION_XX = 'DIVISION_XX',
  CORPS_XXX = 'CORPS_XXX',
  ARMY_XXXX = 'ARMY_XXXX',
}
