export enum UnitSymbolEnum {
  // UNIT SYMBOLS...
  UNKNOWN = 'UNKNOWN',
  INFANTRY = 'INFANTRY',

  UNARMORED_RECON = 'UNARMORED_RECON',
  ARMORED_RECON = 'ARMORED_RECON',
  CAVALRY = 'CAVALRY', // SAME AS UNARMORED RECON...
  MOTORCYCLE_RECON = 'MOTORCYCLE_RECON',

  MOTORIZED_INFANTRY = 'MOTORIZED_INFANTRY',
  ARMORED_INFANTRY = 'ARMORED_INFANTRY',
  TANK = 'TANK', // HVY_AT
  ANTI_TANK = 'ANTI_TANK', // HVY_AT
  ANTI_TANK_MOTORIZED = 'ANTI_TANK_MOTORIZED',
  PIONEERS = 'PIONEERS',
  PIONEERS_MOTORIZED = 'PIONEERS_MOTORIZED',
  MG = 'MG',
  MG_MOTORIZED = 'MG_MOTORIZED',
  BICYCLE = 'BICYCLE',
  FLAMETHROWER = 'FLAMETHROWER',
  RAILROAD = 'RAILROAD',

  ANTI_AIRCRAFT = 'ANTI_AIRCRAFT', // HVY_AT
  ARTILLARY = 'ARTILLARY',
  MOTORIZED_ARTILLARY = 'MOTORIZED_ARTILLARY',
  ASSAULT_GUN = 'ASSAULT_GUN',

  // TRANSPORT UNIT TYPES:
  TRUCK_TRANSPORT = 'TRUCK_TRANSPORT',
  WAGON_TRANSPORT = 'WAGON_TRANSPORT',

  // HQ UNIT TYPES:
  HQ = 'HQ',
  DIVISION_MARKER = 'DIVISION_MARKER',
  SUPPLY_DUMP = 'SUPPLY_DUMP',
}
